In [19]:
import pandas as pd
import random

products = []
random.seed(42)
categories = {
    "Phones": {
        "Apple": ["iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max"],
        "Samsung": ["Galaxy S24", "Galaxy S24+", "Galaxy S24 Ultra", "Galaxy A55"],
        "OnePlus": ["OnePlus 12", "OnePlus 12R", "Nord CE 4", "Nord 4"],
        "Google": ["Pixel 8", "Pixel 8 Pro", "Pixel 8a", "Pixel Fold"],
        "Xiaomi": ["Xiaomi 14", "Redmi Note 13 Pro", "Poco X6 Pro", "Redmi 13"]
    },

    "Laptops": {
        "Dell": ["Inspiron 15", "XPS 13", "Alienware M16", "Latitude 5440"],
        "HP": ["Pavilion 14", "Victus 15", "Spectre x360", "EliteBook 840"],
        "Lenovo": ["IdeaPad Slim 5", "ThinkPad E14", "Legion Pro 5", "Yoga Slim 7"],
        "Asus": ["Vivobook 15", "Zenbook 14", "ROG Strix G16", "TUF A15"],
        "Acer": ["Aspire 7", "Nitro V", "Swift Go", "Predator Helios Neo"]
    },

    "Headphones": {
        "Sony": ["WH-1000XM5", "WF-1000XM5", "CH720N", "INZONE H5"],
        "JBL": ["Tune 770NC", "Live 660NC", "Wave Beam", "Quantum 400"],
        "Boat": ["Rockerz 550", "Nirvana 751", "Airdopes 141", "Immortal 1000D"],
        "Sennheiser": ["HD 450BT", "Momentum 4", "CX Plus", "Accentum"],
        "Noise": ["Noise Two", "Noise Buds VS104", "Noise Airwave", "Noise Three"]
    },

    "Smart Watches": {
        "Apple": ["Watch SE", "Watch Series 9", "Watch Ultra 2", "Watch Nike"],
        "Samsung": ["Galaxy Watch 6", "Galaxy Watch 6 Classic", "Galaxy Watch FE", "Galaxy Watch Ultra"],
        "Noise": ["ColorFit Pro 5", "ColorFit Ultra", "Fit Halo", "Evolve 4"],
        "Fire-Boltt": ["Ninja Call Pro", "Visionary", "Phoenix", "Invincible Plus"],
        "boAt": ["Wave Sigma", "Xtend", "Storm Call", "Lunar Connect"]
    },

    "Cameras": {
        "Canon": ["EOS R50", "EOS R10", "EOS 200D II", "PowerShot G7X"],
        "Nikon": ["Z50", "Zfc", "D7500", "Coolpix P950"],
        "Sony": ["Alpha A6700", "ZV-E10", "Alpha A7 IV", "RX100 VII"],
        "Fujifilm": ["X-T30 II", "X-S20", "X100VI", "Instax Mini Evo"],
        "Panasonic": ["Lumix G85", "Lumix S5 II", "Lumix GH6", "Lumix FZ80"]
    }
}
price_ranges = {
    "Phones": (15000, 120000),
    "Laptops": (30000, 180000),
    "Headphones": (1000, 25000),
    "Smart Watches": (2000, 50000),
    "Cameras": (25000, 250000)
}

descriptions = [
    "High performance device with premium build quality",
    "Designed for everyday use with excellent battery life",
    "Advanced features and powerful processor",
    "Compact design with outstanding performance",
    "Reliable product with modern technology",
    "Best choice for professionals and students",
    "Premium quality with fast performance",
    "Excellent value for money with durable design",
    "Built for gaming and multitasking",
    "Stylish design with cutting-edge features"
]
tags_list = [
    "premium",
    "budget",
    "gaming",
    "professional",
    "portable",
    "wireless",
    "high-performance",
    "best-seller",
    "new-arrival",
    "trending"
]

product_id = 1

for category, details in categories.items():
    for brand, product_list in details.items():
        for product in product_list:

            min_price, max_price = price_ranges[category]

            price = random.randint(min_price, max_price)
            rating = round(random.uniform(3.8, 5.0), 1)
            stock = random.randint(0, 100)

            availability = "In Stock" if stock > 0 else "Out of Stock"

            discount = random.randint(5, 50)

            product_name = f"{brand} {product}"

            description = random.choice(descriptions)

            selected_tags = random.sample(tags_list, 3)

            image_url = f"https://example.com/images/{product_id}.jpg"

            products.append({
                "product_id": product_id,
                "product_name": product_name,
                "category": category,
                "brand": brand,
                "description": description,
                "price": price,
                "discount_percent": discount,
                "final_price": round(price * (1 - discount / 100), 2),
                "rating": rating,
                "stock": stock,
                "availability": availability,
                "tags": ", ".join(selected_tags),
                "image_url": image_url
            })

            product_id += 1

In [20]:
df = pd.DataFrame(products)
print(df.shape)
print(df.head())
df.to_csv("products.csv", index=False)

(100, 13)
   product_id             product_name category    brand  \
0           1          Apple iPhone 15   Phones    Apple
1           2     Apple iPhone 15 Plus   Phones    Apple
2           3      Apple iPhone 15 Pro   Phones    Apple
3           4  Apple iPhone 15 Pro Max   Phones    Apple
4           5       Samsung Galaxy S24   Phones  Samsung

                                         description   price  \
0        Compact design with outstanding performance   98810
1          Stylish design with cutting-edge features  103696
2  High performance device with premium build qua...   27280
3           Advanced features and powerful processor   43893
4  Designed for everyday use with excellent batte...   35379

   discount_percent  final_price  rating  stock availability  \
0                22     77071.80     3.9     94     In Stock
1                10     93326.40     4.7     69     In Stock
2                43     15549.60     4.1     64     In Stock
3                 5     41698.35     4.3     35     In Stock
4                26     26180.46     4.1     97     In Stock

                                          tags  \
0                 professional, gaming, budget
1       high-performance, premium, new-arrival
2  new-arrival, professional, high-performance
3         high-performance, wireless, portable
4           budget, high-performance, trending

                          image_url
0  https://example.com/images/1.jpg
1  https://example.com/images/2.jpg
2  https://example.com/images/3.jpg
3  https://example.com/images/4.jpg
4  https://example.com/images/5.jpg

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        100 non-null    int64
 1   product_name      100 non-null    object
 2   category          100 non-null    object
 3   brand             100 non-null    object
 4   description       100 non-null    object
 5   price             100 non-null    int64
 6   discount_percent  100 non-null    int64
 7   final_price       100 non-null    float64
 8   rating            100 non-null    float64
 9   stock             100 non-null    int64
 10  availability      100 non-null    object
 11  tags              100 non-null    object
 12  image_url         100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

In [22]:
df.describe(include='all')

,product_id,product_name,category,brand,description,price,discount_percent,final_price,rating,stock,availability,tags,image_url
count,100.000000,100,100,100,100,100.000000,100.000000,100.000000,100.000000,100.000000,100,100,100
unique,NaN,100,5,21,10,NaN,NaN,NaN,NaN,NaN,2,96,100
top,NaN,Apple iPhone 15,Phones,Apple,Premium quality with fast performance,NaN,NaN,NaN,NaN,NaN,In Stock,"wireless, professional, budget",https://example.com/images/1.jpg
freq,NaN,1,20,8,13,NaN,NaN,NaN,NaN,NaN,99,2,1
mean,50.500000,NaN,NaN,NaN,NaN,67512.180000,27.450000,49170.781300,4.419000,51.790000,NaN,NaN,NaN
std,29.011492,NaN,NaN,NaN,NaN,56510.681181,12.505655,43484.371797,0.359488,28.236482,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,2386.000000,5.000000,1694.060000,3.800000,0.000000,NaN,NaN,NaN
25%,25.750000,NaN,NaN,NaN,NaN,22876.500000,20.000000,16191.247500,4.100000,31.000000,NaN,NaN,NaN
50%,50.500000,NaN,NaN,NaN,NaN,43819.500000,25.500000,30938.790000,4.400000,52.000000,NaN,NaN,NaN
75%,75.250000,NaN,NaN,NaN,NaN,107170.750000,37.000000,77309.060000,4.700000,73.250000,NaN,NaN,NaN
max,100.000000,NaN,NaN,NaN,NaN,247711.000000,50.000000,220462.790000,5.000000,100.000000,NaN,NaN,NaN

In [23]:
df.isnull().sum().sum()

np.int64(0)

In [24]:
df.duplicated().sum().sum()

np.int64(0)

In [25]:
df.sample(5)

,product_id,product_name,category,brand,description,price,discount_percent,final_price,rating,stock,availability,tags,image_url
20,21,Dell Inspiron 15,Laptops,Dell,Reliable product with modern technology,114975,28,82782.00,4.4,14,In Stock,"professional, premium, trending",https://example.com/images/21.jpg
82,83,Canon EOS 200D II,Cameras,Canon,Advanced features and powerful processor,146905,28,105771.60,4.6,98,In Stock,"trending, budget, gaming",https://example.com/images/83.jpg
85,86,Nikon Zfc,Cameras,Nikon,Designed for everyday use with excellent batte...,116017,28,83532.24,4.4,84,In Stock,"new-arrival, wireless, premium",https://example.com/images/86.jpg
1,2,Apple iPhone 15 Plus,Phones,Apple,Stylish design with cutting-edge features,103696,10,93326.40,4.7,69,In Stock,"high-performance, premium, new-arrival",https://example.com/images/2.jpg
98,99,Panasonic Lumix GH6,Cameras,Panasonic,High performance device with premium build qua...,102659,24,78020.84,4.1,22,In Stock,"new-arrival, gaming, portable",https://example.com/images/99.jpg

In [26]:
df['category'].value_counts()

category
Phones           20
Laptops          20
Headphones       20
Smart Watches    20
Cameras          20
Name: count, dtype: int64

In [27]:
df['brand'].value_counts()

brand
Apple         8
Samsung       8
Sony          8
Noise         8
OnePlus       4
Xiaomi        4
Google        4
Lenovo        4
Dell          4
Asus          4
Acer          4
JBL           4
HP            4
Boat          4
Sennheiser    4
Fire-Boltt    4
boAt          4
Canon         4
Nikon         4
Fujifilm      4
Panasonic     4
Name: count, dtype: int64

In [28]:
df['availability'].value_counts()

availability
In Stock        99
Out of Stock     1
Name: count, dtype: int64

In [29]:
df['rating'].describe()

count    100.000000
mean       4.419000
std        0.359488
min        3.800000
25%        4.100000
50%        4.400000
75%        4.700000
max        5.000000
Name: rating, dtype: float64

In [30]:
df['price'].describe()

count       100.000000
mean      67512.180000
std       56510.681181
min        2386.000000
25%       22876.500000
50%       43819.500000
75%      107170.750000
max      247711.000000
Name: price, dtype: float64

In [32]:
df["combined_features"] = (
    df["product_name"] + " " +
    df["category"] + " " +
    df["brand"] + " " +
    df["description"] + " " +
    df["tags"]
)
df[["product_name", "combined_features"]].head()

              product_name                                  combined_features
0          Apple iPhone 15  Apple iPhone 15 Phones Apple Compact design wi...
1     Apple iPhone 15 Plus  Apple iPhone 15 Plus Phones Apple Stylish desi...
2      Apple iPhone 15 Pro  Apple iPhone 15 Pro Phones Apple High performa...
3  Apple iPhone 15 Pro Max  Apple iPhone 15 Pro Max Phones Apple Advanced ...
4       Samsung Galaxy S24  Samsung Galaxy S24 Phones Samsung Designed for...

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df["combined_features"])
print(tfidf_matrix.shape)

(100, 204)

In [34]:
cosine_sim = cosine_similarity(tfidf_matrix)
print(cosine_sim.shape)

(100, 100)

In [35]:
indices = pd.Series(df.index, index=df["product_name"]).drop_duplicates()
indices.head()

product_name
Apple iPhone 15            0
Apple iPhone 15 Plus       1
Apple iPhone 15 Pro        2
Apple iPhone 15 Pro Max    3
Samsung Galaxy S24         4
dtype: int64

In [36]:
def recommend_products(product_name, top_n=5):

    if product_name not in indices:
        return "Product not found."

    idx = indices[product_name]

    similarity_scores = list(enumerate(cosine_sim[idx]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:top_n+1]

    product_indices = [i[0] for i in similarity_scores]

    return df[[
        "product_name",
        "category",
        "brand",
        "final_price",
        "rating"
    ]].iloc[product_indices]

In [37]:
recommend_products("Apple iPhone 15")

               product_name       category  brand  final_price  rating
2       Apple iPhone 15 Pro         Phones  Apple     15549.60     4.1
1      Apple iPhone 15 Plus         Phones  Apple     93326.40     4.7
61     Apple Watch Series 9  Smart Watches  Apple     29189.93     4.8
3   Apple iPhone 15 Pro Max         Phones  Apple     41698.35     4.3
62      Apple Watch Ultra 2  Smart Watches  Apple     19499.76     4.3

In [38]:
recommend_products("Dell XPS 13")

          product_name    category  brand  final_price  rating
22  Dell Alienware M16     Laptops   Dell    122127.68     4.9
20    Dell Inspiron 15     Laptops   Dell     82782.00     4.4
23  Dell Latitude 5440     Laptops   Dell    142239.59     4.7
85           Nikon Zfc     Cameras  Nikon     83532.24     4.4
42         Sony CH720N  Headphones   Sony     12128.52     4.8

In [39]:
recommend_products("Sony WH-1000XM5")

        product_name    category   brand  final_price  rating
41   Sony WF-1000XM5  Headphones    Sony      5169.00     4.0
43    Sony INZONE H5  Headphones    Sony      3515.46     4.7
88  Sony Alpha A6700     Cameras    Sony     85180.54     4.3
42       Sony CH720N  Headphones    Sony     12128.52     4.8
19   Xiaomi Redmi 13      Phones  Xiaomi     84923.28     4.4

In [40]:
recommend_products("Canon EOS R50")

           product_name category      brand  final_price  rating
81        Canon EOS R10  Cameras      Canon    195998.40     3.8
82    Canon EOS 200D II  Cameras      Canon    105771.60     4.6
83  Canon PowerShot G7X  Cameras      Canon     80967.36     3.9
2   Apple iPhone 15 Pro   Phones      Apple     15549.60     4.1
98  Panasonic Lumix GH6  Cameras  Panasonic     78020.84     4.1

In [41]:
users = pd.DataFrame({
    "user_id": [1,2,3,4,5,6,7,8,9,10],
    "user_name": [
        "Alice","Bob","Charlie","David","Emma",
        "Frank","Grace","Henry","Ivy","Jack"
    ]
})

users

   user_id user_name
0        1     Alice
1        2       Bob
2        3   Charlie
3        4     David
4        5      Emma
5        6     Frank
6        7     Grace
7        8     Henry
8        9       Ivy
9       10      Jack

In [43]:
users.to_csv("users.csv",index=False)

In [42]:
purchase_history = []

random.seed(42)

for user in users["user_id"]:

    purchased_products = random.sample(
        list(df["product_name"]),
        random.randint(2,5)
    )

    for product in purchased_products:

        purchase_history.append({
            "user_id": user,
            "product_name": product
        })

purchase_history = pd.DataFrame(purchase_history)

purchase_history.head()

   user_id              product_name
0        1   Apple iPhone 15 Pro Max
1        1           Fujifilm X100VI
2        2        Lenovo Yoga Slim 7
3        2     Lenovo IdeaPad Slim 5
4        2  Xiaomi Redmi Note 13 Pro

In [44]:
purchase_history.to_csv("purchase_history.csv",index=False)

In [45]:
purchase_history

    user_id                product_name
0         1     Apple iPhone 15 Pro Max
1         1             Fujifilm X100VI
2         2          Lenovo Yoga Slim 7
3         2       Lenovo IdeaPad Slim 5
4         2    Xiaomi Redmi Note 13 Pro
5         2             Fujifilm X100VI
6         3                 Nikon D7500
7         3             Fujifilm X100VI
8         4  Fire-Boltt Invincible Plus
9         4          Sennheiser CX Plus
10        5     Apple iPhone 15 Pro Max
11        5              OnePlus Nord 4
12        6         Lenovo ThinkPad E14
13        6      Samsung Galaxy Watch 6
14        6                  boAt Xtend
15        7              Noise Evolve 4
16        7                HP Victus 15
17        8       Lenovo IdeaPad Slim 5
18        8      Noise Noise Buds VS104
19        8  Fire-Boltt Invincible Plus
20        8                Asus TUF A15
21        8             Apple iPhone 15
22        9                 Sony ZV-E10
23        9          Sennheiser CX Plus
24        9              Sony INZONE H5
25       10             Xiaomi Redmi 13
26       10            HP EliteBook 840
27       10       Panasonic Lumix S5 II
28       10              Sony INZONE H5

In [46]:
def recommend_for_user(user_id, top_n=5):

    purchased = purchase_history[
        purchase_history["user_id"] == user_id
    ]["product_name"].tolist()

    if len(purchased)==0:
        return "No purchase history found."

    recommendations=[]

    for product in purchased:

        if product in indices:

            idx=indices[product]

            scores=list(enumerate(cosine_sim[idx]))

            scores=sorted(
                scores,
                key=lambda x:x[1],
                reverse=True
            )

            scores=scores[1:top_n+1]

            for score in scores:

                recommendations.append(score[0])

    recommendations=list(dict.fromkeys(recommendations))

    purchased_indices=df[
        df["product_name"].isin(purchased)
    ].index

    recommendations=[
        r for r in recommendations
        if r not in purchased_indices
    ]

    return df.iloc[
        recommendations[:top_n]
    ][[
        "product_name",
        "category",
        "brand",
        "final_price",
        "rating"
    ]]

In [47]:
recommend_for_user(1)

            product_name       category  brand  final_price  rating
2    Apple iPhone 15 Pro         Phones  Apple     15549.60     4.1
60        Apple Watch SE  Smart Watches  Apple      7577.44     4.3
0        Apple iPhone 15         Phones  Apple     77071.80     3.9
1   Apple iPhone 15 Plus         Phones  Apple     93326.40     4.7
61  Apple Watch Series 9  Smart Watches  Apple     29189.93     4.8

In [48]:
recommend_for_user(3)

            product_name       category  brand  final_price  rating
85             Nikon Zfc        Cameras  Nikon     83532.24     4.4
87    Nikon Coolpix P950        Cameras  Nikon     75146.40     4.0
84             Nikon Z50        Cameras  Nikon     35937.60     4.5
77            boAt Xtend  Smart Watches   boAt     36711.00     4.5
68  Noise ColorFit Pro 5  Smart Watches  Noise     19532.52     4.5

In [49]:
purchase_history[
    purchase_history["user_id"]==1
]

   user_id             product_name
0        1  Apple iPhone 15 Pro Max
1        1          Fujifilm X100VI

In [50]:
preferences = pd.DataFrame({
    "user_id":[1,2,3,4,5,6,7,8,9,10],
    "preferred_category":[
        "Phones",
        "Laptops",
        "Headphones",
        "Smart Watches",
        "Cameras",
        "Phones",
        "Laptops",
        "Headphones",
        "Smart Watches",
        "Cameras"
    ]
})

preferences

   user_id preferred_category
0        1             Phones
1        2            Laptops
2        3         Headphones
3        4      Smart Watches
4        5            Cameras
5        6             Phones
6        7            Laptops
7        8         Headphones
8        9      Smart Watches
9       10            Cameras

In [51]:
preferences.to_csv("preferences.csv",index=False)

In [52]:
def recommend_by_preference(user_id, top_n=5):

    category = preferences.loc[
        preferences["user_id"] == user_id,
        "preferred_category"
    ].values[0]

    products = df[
        df["category"] == category
    ]

    return products.sort_values(
        by=["rating","stock"],
        ascending=False
    )[
        [
            "product_name",
            "brand",
            "category",
            "rating",
            "final_price"
        ]
    ].head(top_n)

In [53]:
recommend_by_preference(8)

           product_name       brand    category  rating  final_price
54   Sennheiser CX Plus  Sennheiser  Headphones     5.0     17216.84
55  Sennheiser Accentum  Sennheiser  Headphones     5.0     18622.32
50    Boat Airdopes 141        Boat  Headphones     5.0      4363.56
47      JBL Quantum 400         JBL  Headphones     4.9      2979.90
42          Sony CH720N        Sony  Headphones     4.8     12128.52